// Build script: scans the vault for .md files and bundles them into data.js
// Usage:  node scripts/build.js
// Output: webapp/data.js  (loaded by index.html — no server needed)

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const OUT_DIR = path.resolve(__dirname, '..');
const OUT = path.join(OUT_DIR, 'data.js');

const IGNORE_DIRS = new Set(['webapp', 'node_modules', '.git', '.obsidian', 'avocato', '_archive']);

function walk(dir, base, results) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || IGNORE_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, base, results);
    else if (entry.name.endsWith('.md')) {
      results.push(path.relative(base, full).replace(/\\/g, '/'));
    }
  }
  return results;
}

const files = walk(ROOT, ROOT, []).sort();

const data = files.map((rel) => {
  const full = path.join(ROOT, rel);
  const raw = fs.readFileSync(full, 'utf8');
  const content = raw.replace(/^\uFEFF/, '');
  const firstHeading = content.split('\n').map((l) => l.trim()).find((l) => l.startsWith('# '));
  const title = firstHeading ? firstHeading.slice(2).trim().replace(/^\uFEFF/, '') : rel;
  const parts = rel.split('/');
  const folder = parts.length > 1 ? parts[0] : '(root)';
  const file = parts.slice(1).join('/') || parts[0];
  const words = content.split(/\s+/).filter(Boolean).length;
  return { id: rel, folder, file, title, content, words };
});

const banner = '// AUTO-GENERATED by scripts/build.js — do not edit manually.\n// Rebuild after editing any .md file:  node scripts/build.js\n';
const out = banner + 'window.VAULT_DATA = ' + JSON.stringify(data) + ';\n';
fs.writeFileSync(OUT, out, 'utf8');

console.log(`✓ Built ${data.length} documents -> webapp/data.js (${(out.length / 1024).toFixed(1)} KB)`);
