// One-time font pipeline: fetch the latin woff2 subsets from Google Fonts,
// store them in webapp/fonts/, and emit webapp/fonts.css with local URLs.
// Google serves variable fonts for these families: one file per family/style.
// Usage: node webapp/scripts/fetch-fonts.mjs (requires network; run once).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = path.join(ROOT, 'webapp', 'fonts');
const CSS_OUT = path.join(ROOT, 'webapp', 'fonts.css');

const GF = 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400..700;1,400..700&family=Inter:wght@400..700&family=JetBrains+Mono:wght@400..600&display=swap';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// family → { slug, weightRange } (ranges as requested above)
const FAMILIES = {
  'Cormorant Garamond': { slug: 'cormorant', range: '400 700' },
  Inter: { slug: 'inter', range: '400 700' },
  'JetBrains Mono': { slug: 'mono', range: '400 600' }
};

const res = await fetch(GF, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`Google Fonts CSS HTTP ${res.status}`);
const css = await res.text();

const picked = new Map(); // "family|style" -> { family, style, src, file }
for (const block of css.split('@font-face').slice(1)) {
  const body = block.slice(0, block.indexOf('}'));
  const family = (body.match(/font-family:\s*'([^']+)'/) || [])[1];
  const style = (body.match(/font-style:\s*(\w+)/) || [])[1];
  const src = (body.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
  const range = (body.match(/unicode-range:\s*([^;]+);/) || [])[1] || '';
  const meta = FAMILIES[family];
  if (!meta || !src || !/U\+0000-00FF/i.test(range)) continue;
  const key = `${family}|${style}`;
  if (!picked.has(key)) picked.set(key, { family, style, src, file: `${meta.slug}${style === 'italic' ? '-italic' : ''}.woff2` });
}
if (!picked.size) throw new Error('No latin faces parsed — Google CSS format may have changed');

fs.mkdirSync(OUT, { recursive: true });
for (const f of fs.readdirSync(OUT)) if (f.endsWith('.woff2')) fs.unlinkSync(path.join(OUT, f));

let bytes = 0;
for (const f of picked.values()) {
  const r = await fetch(f.src, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`Font download HTTP ${r.status} for ${f.file}`);
  const buf = Buffer.from(await r.arrayBuffer());
  fs.writeFileSync(path.join(OUT, f.file), buf);
  bytes += buf.length;
  console.log(`fetched ${f.file} (${(buf.length / 1024).toFixed(1)} KB) — ${f.family} ${f.style} ${FAMILIES[f.family].range}`);
}

const local = ['/* Self-hosted OFL fonts (latin subset, variable) — generated by scripts/fetch-fonts.mjs. Do not edit. */',
  ...[...picked.values()].map((f) => `@font-face{font-family:'${f.family}';font-style:${f.style};font-weight:${FAMILIES[f.family].range};font-display:swap;src:url(fonts/${f.file}) format('woff2')}`)].join('\n') + '\n';
fs.writeFileSync(CSS_OUT, local, 'utf8');

const OFL = {
  'OFL-CormorantGaramond.txt': 'https://raw.githubusercontent.com/google/fonts/main/ofl/cormorantgaramond/OFL.txt',
  'OFL-Inter.txt': 'https://raw.githubusercontent.com/google/fonts/main/ofl/inter/OFL.txt',
  'OFL-JetBrainsMono.txt': 'https://raw.githubusercontent.com/google/fonts/main/ofl/jetbrainsmono/OFL.txt'
};
for (const [name, url] of Object.entries(OFL)) {
  try {
    const r = await fetch(url, { headers: { 'User-Agent': UA } });
    if (r.ok) fs.writeFileSync(path.join(OUT, name), await r.text(), 'utf8');
    else console.log(`license skipped (${r.status}): ${name}`);
  } catch { console.log(`license skipped: ${name}`); }
}

console.log(`\nDone: ${picked.size} woff2, ${(bytes / 1024).toFixed(0)} KB total -> webapp/fonts/ + webapp/fonts.css`);
